apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-controller-config
  namespace: cert-manager
data:
  config.yaml: |
    apiVersion: controller.config.cert-manager.io/v1alpha1
    kind: ControllerConfiguration
    enableGatewayAPI: true
